# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import threads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('content', models.TextField(blank=True, default='', max_length=1024)),
                ('author', models.ForeignKey(on_delete=models.SET(threads.models.get_null_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
