# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=1024)),
                ('slug', models.SlugField()),
                ('key', models.CharField(max_length=6)),
            ],
        ),
    ]
