# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field=250, upload_to='', width_field=250),
        ),
    ]
